### ISSUE TITLE
Number of zones hard-coded

### ISSUE THREAD

**Issue by jrothlis** [andrew-blake/evohome-utils#1]
Hi Andrew,

I just found this today and have been playing around with it. I've found a few issues that I'd like to report.

The number of zones is hard-coded (currently 0-13), and should be dynamic.

I have 8 zones plus DHW, and if I set mine 0-8 I don't get the DHW, but if I set it 0-9 I think the temperatures being logged are off by one (i.e. the temperatures don't match with the zone).

**Comment by andrew-blake** [comment]
Currently the log_temp script logs to both CSV (original version), and more recently to influxdb - and unfortunately that does currently require hardcoded zone names - in the numerical zone order returned by the API. Not great but it currently works.

I'm thinking of refactoring the influx logging into a separate script since the influxdb allows for great visualisation using Grafana. And once CSV isn't part of it that would allow the zones values to just be obtained dynamically from the EvoHome API response.

**Comment by jrothlis** [comment]
Thanks! I just this minute got my Grafana graphing working, and it's incredible. It's a lot of fun!

One more suggestion: DHW should be a separate type of data, like dhw.actual instead of zone.actual -- this makes it easier to graph all zones except for DHW (it's still possible to exclude, but that way you would also get rid of that fake -1 you are adding).

I think as soon as you get rid of the CSV stuff, the script will be 100x cleaner.

**Comment by andrew-blake** [comment]
That's a good idea. I think in short term I'll probably just not send any data for the target. At the time I didn't realise I could get away without having any target points for DHW.

Btw, this is how I visualise my DHW - keeping it separate from the main zones.

![image](https://cloud.githubusercontent.com/assets/1393000/12404736/1e0022de-be36-11e5-9c56-dd48e73fa2f1.png)

**Comment by jrothlis** [comment]
Thanks Andrew. I'm going to have a bit of a stab tomorrow to see if I can come up with something. If I'm successful, I'll share it with you.

--John

**Comment by andrew-blake** [comment]
I've refactored the code so it doesn't require the zone names in the config file.

Also split the CSV and Influx logging into separate scripts. It's much cleaner now.

**Comment by andrew-blake** [comment]
Btw, there is a new parameter in each of the config.py and influx_config.py file - look at the samples

**Comment by jrothlis** [comment]
Funny coincidence, the Honeywell API evangelist popped into the Automated Home forum today to say that we're using an old URL for the API access. Long story short, there's a new URL, the evohome client has been updated, which appears to resolve the 404 errors!!

https://github.com/watchforstock/evohome-client/commit/78961ce30c6bffd61b25df3420694cc01d7b52e1
