### ISSUE TITLE
Possible to use API v1?

### ISSUE THREAD

**Issue by jrothlis** [andrew-blake/evohome-utils#3]
API v2 is notoriously buggy. I have mine logging every minute (just for testing), and there are sometimes 2 or 3 minute gaps in the data. If I run logtemp.py manually, I randomly get 404 errors, and re-running will sometimes succeed, and sometimes will result in another 404.

I've read on the forums that the v1 API is a lot more reliable.

**Comment by andrew-blake** [comment]
I've not used the V1 API for a long time. I know it doesn't have some of the schedule backup / restore capabilities I added to V2 - but I guess that's not technically needed for temperature logging.

Btw, I get around this by setting Grafana to assume missing data points are the same value as the previous ones - null point mode = connected.

![image](https://cloud.githubusercontent.com/assets/1393000/12404705/bc12a556-be35-11e5-9612-dd4009302452.png)

**Comment by andrew-blake** [comment]
I've added an exception handler, so it should at least trap the EvoHome API errors.

Personally I'm not going to switch to V1 as the grafana null point drawing means the gaps aren't an issue, but if you want to create a pull request, I can review.
